server:
  port: 8085
spring:
  application:
    name: notifications-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: arkastorenotification@gmail.com

    password: mtmb abku ikdn bfll
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: paymentAcceptedEventListener;paymentRejectedEventListener;shippingSendEventListener;reportSendEventListener
    stream:
      bindings:
        paymentAcceptedEventListener-in-0:
          destination: payment.accepted.exchange
          content-type: application/json
          group: notification-service-group
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-max-interval: 10000
        paymentRejectedEventListener-in-0:
          destination: payment.rejected.exchange
          content-type: application/json
          group: notification-service-group
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-max-interval: 10000
        shippingSendEventListener-in-0:
          destination: shipping.send.exchange
          content-type: application/json
          group: notification-service-group
          consumer:
            max-attempts: 3
            back-off-initial-interval: 1000
            back-off-max-interval: 10000
        reportSendEventListener-in-0:
          destination: report.send.exchange
          content-type: application/json
          group: notification-service-group
  management:
    endpoints:
      web:
        exposure:
          include: busrefresh

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: shipping
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus